apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv0002-cl
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: pv0002
