apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "torchserve"
spec:
  predictor:
    pytorch:
      storageUri: pvc://pv0002-cl/
      resources:
        limits:
          memory: 4Gi
          nvidia.com/gpu: "0"
